#!/usr/bin/env python3
"""Regenerate docs/leaderboards.md from experiments/*/record.json.

The table is generated, never hand-edited. That is what keeps 16 categories from
fighting over one file: an experiment branch writes only its own record.json, and
the table is re-rendered on autofarmer after a merge. The output is deterministic,
so re-running on an unchanged tree produces no diff.

    python3 tools/render_leaderboards.py [--check]

--check exits non-zero if the file on disk is stale, for use in the loop.
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "leaderboards.md"

HEADER = """# Leaderboards

Generated by `tools/render_leaderboards.py` from `experiments/*/record.json`.
**Do not edit by hand** — edit the record file for the category instead.

Every category runs `leaderboard_run(Leaderboards.<name>, "main", <speedup>)` from
`saves/<slug>/Runner.py`. Runs repeat until 2 h of simulated time and the
**average** is what gets uploaded, so a single fast run is not a score.

| Leaderboard | Slug | Mode | Target | PB | Rank | Status |
| --- | --- | --- | --- | --- | --- | --- |
"""

FOOTER = """
Status values: `baseline` — has a measured time · `seeded` — has code from the
matching achievement, not yet scored · `empty` — no driver written yet.

Branch convention: `auto_experiment/<slug>/<NNN>`, numbered per category.
"""


def rows():
    for rec in sorted((REPO / "experiments").glob("*/record.json")):
        d = json.loads(rec.read_text())
        yield (
            d["leaderboard"], d["slug"], d["mode"], d["target"],
            d.get("personal_best") or "—",
            f"#{d['global_rank']}" if d.get("global_rank") else "—",
            d.get("status", "—"),
        )


def render():
    body = "".join("| " + " | ".join(r) + " |\n" for r in rows())
    return HEADER + body + FOOTER


def main():
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(REPO)} is stale — re-run without --check")
            return 1
        print("leaderboards.md is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)} ({sum(1 for _ in rows())} categories)")
    return 0


sys.exit(main())
